services:
  database:
    container_name: db_api_inventario
    image: postgres:16
    environment:
      POSTGRES_DB: db_inventario
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: proyecto_poo
    ports:
      - "5433:5432"
    volumes:
      - db_inventario_data:/var/lib/postgresql/data

volumes:
  db_inventario_data: