spring.application.name=GestionInventarioAPI

# db
spring.datasource.url=jdbc:postgresql://localhost:5433/db_inventario
spring.datasource.username=postgres
spring.datasource.password=proyecto_poo
spring.datasource.driver-class-name=org.postgresql.Driver

# jpa
spring.jpa.database=POSTGRESQL
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true